spring:
  datasource:
    username: sa
    url: jdbc:h2:./data/keycloak

server:
  context-path: /
  port: 8080

resteasy:
  deployment:
    async_job_service_enabled: true


management:
  context-path: /actuator
  security:
    enabled: true
    roles: MANAGER

keycloak:
  server:
    contextPath: /auth

security:
  user:
    name: manager
    password: manager
    role: MANAGER

  basic:
    enabled: true
    path: /mgmt
