spring:
  datasource:
    username: sa
    url: jdbc:h2:./data/keycloak;DB_CLOSE_ON_EXIT=FALSE

server:
  port: 8080

resteasy:
  deployment:
    async_job_service_enabled: true

keycloak:
  server:
    contextPath: /auth
